adwords:
  developer_token: Bs09ro03bYmLUDm1iMJFYg
  client_id: 202284741493-a72fr1pdgbi6r4b5ipula4vcrsmof4bf.apps.googleusercontent.com
  client_secret: 64I_RcTpxRMWEQC-VdDbnDpn
  refresh_token: 1//09KY9pP01-mn1CgYIARAAGAkSNwF-L9IrZ2hvyFB56yq93Y7C3-FMoQbF6QhkC3tCpwepU98PJMu4xNwlVcqQDIIjMcZPR1yqUAY
  client_customer_id: 234-548-8039

fb_marketing:
  app_id: "1087573895408523"
  app_secret: 6e01d697a935b056a982ef623fde14e2
  access_token: EAAPdJIez64sBANARqKZCgk3thHg0TBGF2mDEDMiLVcqzN5atKGO3riXsVr6Lzmi59mZAtLhCYeKuXWwO5R5ZB0foh0rx4I5iy0ZCIGUdOcArnGzZAniBWIWRZApNlItimDlS4ZC8InLgIscVzYq1RD580ZCgZAr04eQE7obBPM3dF29ds6bN6QWEK
  account_id: act_388606526375999
